### PR TITLE
Updated the base template

### PR DESCRIPTION
**Pull request by iev6**
Made the template more presentable, and included mailto links for email.

### CODE REVIEW

**Comment by akshayrangasai** [comment]
Can you merge master, resolve conflicts and re-send request?

**Comment by iev6** [comment]
Thalaivaaa look who's back to form. Will do.

On 26-Dec-2016 10:47, "akshayrangasai" <notifications@github.com> wrote:

Can you merge master, resolve conflicts and re-send request?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/akshayrangasai/IITMLatextResume/pull/2#issuecomment-269163487>,
or mute the thread

**Comment by iev6** [comment]
Can you tell me what conflicts pop up? I don't see anything in my fork. Or better, you can add me as a collaborator if you can.

**Comment by akshayrangasai** [comment]
Added you as a contributor. I will add more templates and update the repo. Pull and readd pls.

Thanksm

**Pull request merged**
